### ISSUE TITLE
any bug in circshift()??

### ISSUE THREAD

**Issue by Thanh-Binh** [DodgeHo/VMD_cpp#1]
as far as I understood, this util function does shift the data array by offset positions
negative/positive offset means move to left/right
For example: 
    d = [0, 1, 2, 3, 4, 5, 6]
    output by offset = 4 : [4, 5, 6, 0, 1, 2, 3]
    output by offset = -2: [2, 3, 4, 5, 6, 0, 1]

If so, I believe this utils is uncorrect.
What do you think?

Instead, I rewrite this function as follows:
###########################################
```C
vectorcd circshift(vectorcd& data, int offset)
{
	int n = int(data.size());
	if (offset == 0) {
		vectorcd out_data(data);
		return out_data;
	}
	else
	{
		if (offset > 0) offset = n - offset;		// move to right by offset positions
		else              offset = -offset;			// move to left by offset positions
		vectorcd out_data(data.begin() + offset, data.end());
		out_data.insert(out_data.end(), data.begin(), data.begin() + offset);
		return out_data;
	}
}
```

**Comment by DodgeHo** [comment]
I change this function as yours.
